/**
 * Fresh Editor TypeScript Plugin API
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by fresh-plugin-api-macros
 */

/**
 * Get the editor API instance.
 * Plugins must call this at the top of their file to get a scoped editor object.
 */
declare function getEditor(): EditorAPI;

/** Handle for a cancellable async operation */
interface ProcessHandle<T> extends PromiseLike<T> {
  /** Promise that resolves to the result when complete */
  readonly result: Promise<T>;
  /** Cancel/kill the operation. Returns true if cancelled, false if already completed */
  kill(): Promise<boolean>;
}

/** Buffer identifier */
type BufferId = number;

/** Split identifier */
type SplitId = number;

/** Buffer information */
interface BufferInfo {
  id: number;
  path: string;
  modified: boolean;
  length: number;
}

/** Cursor information with optional selection */
interface CursorInfo {
  position: number;
  selection?: { start: number; end: number } | null;
}

/** Viewport information */
interface ViewportInfo {
  top_byte: number;
  left_column: number;
  width: number;
  height: number;
}

/** Result from spawnProcess */
interface SpawnResult {
  stdout: string;
  stderr: string;
  exit_code: number;
}

/** Result from spawnBackgroundProcess */
interface BackgroundProcessResult {
  process_id: number;
}

/** Directory entry */
interface DirEntry {
  name: string;
  is_file: boolean;
  is_dir: boolean;
}

/** File stat information */
interface FileStat {
  exists: boolean;
  is_file: boolean;
  is_dir: boolean;
  size: number;
  readonly: boolean;
}

/** Prompt suggestion */
interface PromptSuggestion {
  text: string;
  description?: string | null;
  value?: string | null;
  disabled?: boolean | null;
  keybinding?: string | null;
}

/** Text property entry for virtual buffers */
interface TextPropertyEntry {
  text: string;
  properties: Record<string, unknown>;
}

/** Result from createVirtualBufferInSplit */
interface CreateVirtualBufferResult {
  buffer_id: number;
  split_id?: number | null;
}

/**
 * Main editor API interface
 */
interface EditorAPI {
  /**
   * Display a transient message in the editor's status bar
   */
  setStatus(message: string): void;

  /**
   * Log a debug message (appears in log file with RUST_LOG=debug)
   */
  debug(message: string): void;

  /**
   * Log an error message
   */
  error(message: string): void;

  /**
   * Log a warning message
   */
  warn(message: string): void;

  /**
   * Log an info message
   */
  info(message: string): void;

  /**
   * Get the active buffer ID (0 if none)
   */
  getActiveBufferId(): number;

  /**
   * Get the active split ID
   */
  getActiveSplitId(): number;

  /**
   * Get cursor byte position in active buffer
   */
  getCursorPosition(): number;

  /**
   * Get cursor line number (1-indexed)
   */
  getCursorLine(): number;

  /**
   * Get file path for a buffer (empty string if no path)
   */
  getBufferPath(bufferId: number): string;

  /**
   * Get buffer length in bytes
   */
  getBufferLength(bufferId: number): number;

  /**
   * Check if buffer has unsaved changes
   */
  isBufferModified(bufferId: number): boolean;

  /**
   * List all open buffers
   */
  listBuffers(): BufferInfo[];

  /**
   * Get primary cursor info as JSON
   */
  getPrimaryCursor(): string;

  /**
   * Get all cursors as JSON
   */
  getAllCursors(): string;

  /**
   * Get all cursor positions as array
   */
  getAllCursorPositions(): number[];

  /**
   * Get viewport info as JSON
   */
  getViewport(): string;

  /**
   * Get buffer info (returns JSON, parsed in JS)
   */
  getBufferInfo(bufferId: number): string;

  /**
   * Get text properties at cursor position (returns JSON array)
   */
  getTextPropertiesAtCursor(bufferId: number): string;

  /**
   * Get the current editor mode (for modal editing)
   */
  getEditorMode(): string | null;

  /**
   * Get diff vs last saved snapshot (returns JSON)
   */
  getBufferSavedDiff(bufferId: number): string;

  /**
   * Get all LSP diagnostics (returns JSON array)
   */
  getAllDiagnostics(): string;

  /**
   * Check if a background process is still running
   */
  isProcessRunning(processId: number): boolean;

  /**
   * Get merged config as JSON string
   */
  getConfig(): string;

  /**
   * Get user config only as JSON string
   */
  getUserConfig(): string;

  /**
   * Get config directory path
   */
  getConfigDir(): string;

  /**
   * Get themes directory path
   */
  getThemesDir(): string;

  /**
   * Reload configuration from file
   */
  reloadConfig(): void;

  /**
   * Get the current locale
   */
  getCurrentLocale(): string;

  /**
   * Get theme JSON schema
   */
  getThemeSchema(): string;

  /**
   * Get built-in themes as JSON
   */
  getBuiltinThemes(): string;

  /**
   * Apply a theme by name
   */
  applyTheme(themeName: string): void;

  /**
   * Delete a theme (sync, returns success)
   */
  deleteThemeSync(name: string): boolean;

  /**
   * Copy text to system clipboard
   */
  setClipboard(text: string): void;

  /**
   * Copy text to clipboard (alias)
   */
  copyToClipboard(text: string): void;

  /**
   * Insert text at a byte position in a buffer
   */
  insertText(bufferId: number, position: number, text: string): boolean;

  /**
   * Delete a byte range from a buffer
   */
  deleteRange(bufferId: number, start: number, end: number): boolean;

  /**
   * Insert text at the current cursor position
   */
  insertAtCursor(text: string): boolean;

  /**
   * Open a file, optionally at a specific location
   */
  openFile(path: string, line: number, column: number): boolean;

  /**
   * Open a file in a specific split
   */
  openFileInSplit(splitId: number, path: string, line: number, column: number): boolean;

  /**
   * Show a buffer in the current split
   */
  showBuffer(bufferId: number): boolean;

  /**
   * Close a buffer
   */
  closeBuffer(bufferId: number): boolean;

  /**
   * Find a buffer by its file path
   */
  findBufferByPath(path: string): number;

  /**
   * Focus a specific split
   */
  focusSplit(splitId: number): boolean;

  /**
   * Set the buffer displayed in a split
   */
  setSplitBuffer(splitId: number, bufferId: number): boolean;

  /**
   * Close a split
   */
  closeSplit(splitId: number): boolean;

  /**
   * Set cursor position in a buffer
   */
  setBufferCursor(bufferId: number, position: number): boolean;

  /**
   * Set split scroll position
   */
  setSplitScroll(splitId: number, topByte: number): boolean;

  /**
   * Set split ratio
   */
  setSplitRatio(splitId: number, ratio: number): boolean;

  /**
   * Distribute all splits evenly
   */
  distributeSplitsEvenly(): boolean;

  /**
   * Add a visual overlay (internal, takes JSON)
   */
  _addOverlayInternal(json: string): boolean;

  /**
   * Clear all overlays in a namespace
   */
  clearNamespace(bufferId: number, namespace: string): boolean;

  /**
   * Clear all overlays from a buffer
   */
  clearAllOverlays(bufferId: number): boolean;

  /**
   * Remove a specific overlay by handle
   */
  removeOverlay(bufferId: number, handle: string): boolean;

  /**
   * Clear overlays in a byte range
   */
  clearOverlaysInRange(bufferId: number, start: number, end: number): boolean;

  /**
   * Add virtual text at a position
   */
  addVirtualText(bufferId: number, virtualTextId: string, position: number, text: string, r: number, g: number, b: number, before: boolean, useBg: boolean): boolean;

  /**
   * Remove virtual text by ID
   */
  removeVirtualText(bufferId: number, virtualTextId: string): boolean;

  /**
   * Remove virtual texts by prefix
   */
  removeVirtualTextsByPrefix(bufferId: number, prefix: string): boolean;

  /**
   * Clear all virtual texts from a buffer
   */
  clearVirtualTexts(bufferId: number): boolean;

  /**
   * Clear virtual texts in a namespace
   */
  clearVirtualTextNamespace(bufferId: number, namespace: string): boolean;

  /**
   * Add a virtual line
   */
  addVirtualLine(bufferId: number, position: number, text: string, fgR: number, fgG: number, fgB: number, bgR: number, bgG: number, bgB: number, above: boolean, namespace: string, priority: number): boolean;

  /**
   * Set a line indicator (internal, takes JSON)
   */
  _setLineIndicatorInternal(json: string): boolean;

  /**
   * Set a line indicator in the gutter
   */
  setLineIndicator(bufferId: number, line: number, namespace: string, symbol: string, r: number, g: number, b: number, priority: number): boolean;

  /**
   * Clear line indicators in a namespace
   */
  clearLineIndicators(bufferId: number, namespace: string): boolean;

  /**
   * Set file explorer decorations (takes JSON)
   */
  setFileExplorerDecorations(namespace: string, decorationsJson: string): boolean;

  /**
   * Clear file explorer decorations
   */
  clearFileExplorerDecorations(namespace: string): boolean;

  /**
   * Enable/disable line numbers for a buffer
   */
  setLineNumbers(bufferId: number, enabled: boolean): boolean;

  /**
   * Force refresh of line display
   */
  refreshLines(bufferId: number): boolean;

  /**
   * Start an interactive prompt
   */
  startPrompt(label: string, promptType: string): boolean;

  /**
   * Start a prompt with initial value
   */
  startPromptWithInitial(label: string, promptType: string, initialValue: string): boolean;

  /**
   * Set suggestions for the current prompt (takes JSON)
   */
  setPromptSuggestions(suggestionsJson: string): boolean;

  /**
   * Register a custom command (internal)
   */
  _registerCommandInternal(pluginName: string, name: string, description: string, handlerName: string, context: string | null): boolean;

  /**
   * Unregister a command
   */
  unregisterCommand(name: string): boolean;

  /**
   * Set a custom context
   */
  setContext(name: string, active: boolean): boolean;

  /**
   * Execute a built-in action
   */
  executeAction(actionName: string): boolean;

  /**
   * Execute multiple actions (takes JSON)
   */
  executeActions(actionsJson: string): boolean;

  /**
   * Set the global editor mode
   */
  setEditorMode(mode: string | null): boolean;

  /**
   * Define a buffer mode (takes JSON for bindings)
   */
  defineMode(name: string, parent: string | null, bindingsJson: string): boolean;

  /**
   * Subscribe to an editor event
   */
  on(eventName: string, handlerName: string): boolean;

  /**
   * Unsubscribe from an event
   */
  off(eventName: string, handlerName: string): boolean;

  /**
   * Get list of handlers for an event
   */
  getHandlers(eventName: string): string[];

  /**
   * Get environment variable
   */
  getEnv(name: string): string | null;

  /**
   * Get current working directory
   */
  getCwd(): string;

  /**
   * Join path segments
   */
  pathJoin(parts: string[]): string;

  /**
   * Get directory name
   */
  pathDirname(path: string): string;

  /**
   * Get base name
   */
  pathBasename(path: string): string;

  /**
   * Get file extension
   */
  pathExtname(path: string): string;

  /**
   * Check if path is absolute
   */
  pathIsAbsolute(path: string): boolean;

  /**
   * Check if file exists
   */
  fileExists(path: string): boolean;

  /**
   * Read file contents (sync)
   */
  readFileSync(path: string): string | null;

  /**
   * Write file contents (sync)
   */
  writeFileSync(path: string, content: string): boolean;

  /**
   * Read directory contents as JSON
   */
  readDir(path: string): string;

  /**
   * Get file stat info as JSON
   */
  fileStat(path: string): string;

  /**
   * Translate a plugin string (internal)
   */
  _pluginTranslate(pluginName: string, key: string, argsJson: string): string;

  /**
   * Create a scroll sync group
   */
  createScrollSyncGroup(groupId: number, leftSplit: number, rightSplit: number): boolean;

  /**
   * Set scroll sync anchors (takes JSON)
   */
  setScrollSyncAnchors(groupId: number, anchorsJson: string): boolean;

  /**
   * Remove a scroll sync group
   */
  removeScrollSyncGroup(groupId: number): boolean;

  /**
   * Show an action popup (takes JSON)
   */
  showActionPopup(optionsJson: string): boolean;

  /**
   * Disable LSP for a language
   */
  disableLspForLanguage(language: string): boolean;

  /**
   * Submit a view transform (takes JSON)
   */
  submitViewTransform(bufferId: number, splitId: number | null, start: number, end: number, tokensJson: string, layoutHintsJson: string | null): boolean;

  /**
   * Clear view transform
   */
  clearViewTransform(bufferId: number, splitId: number | null): boolean;

  /**
   * Delay execution for specified milliseconds
   */
  delay(durationMs: number): Promise<void>;

  /**
   * Get text from a buffer range
   */
  getBufferText(bufferId: number, start: number, end: number): Promise<string>;

  /**
   * Read file contents (async)
   */
  readFile(path: string): Promise<string>;

  /**
   * Write file contents (async)
   */
  writeFile(path: string, content: string): Promise<void>;

  /**
   * Delete a theme (async)
   */
  deleteTheme(name: string): Promise<void>;

  /**
   * Send an LSP request
   */
  sendLspRequest(language: string, method: string, paramsJson: string | null): Promise<string>;

  /**
   * Get syntax highlights for a range
   */
  getHighlights(bufferId: number, start: number, end: number): Promise<string>;

  /**
   * Kill a background process
   */
  killProcess(processId: number): Promise<boolean>;

  /**
   * Wait for a spawned process
   */
  spawnProcessWait(processId: number): Promise<string>;

  /**
   * Create a virtual buffer in current split (takes JSON options)
   */
  createVirtualBuffer(optionsJson: string): Promise<number>;

  /**
   * Create a virtual buffer in a new split (takes JSON options)
   */
  createVirtualBufferInSplit(optionsJson: string): Promise<string>;

  /**
   * Create a virtual buffer in an existing split (takes JSON options)
   */
  createVirtualBufferInExistingSplit(optionsJson: string): Promise<number>;

  /**
   * Set virtual buffer content (takes JSON entries)
   */
  setVirtualBufferContent(bufferId: number, entriesJson: string): boolean;

  /**
   * Create a composite buffer (takes JSON options)
   */
  createCompositeBuffer(optionsJson: string): Promise<number>;

  /**
   * Update composite buffer alignment (takes JSON hunks)
   */
  updateCompositeAlignment(bufferId: number, hunksJson: string): boolean;

  /**
   * Close a composite buffer
   */
  closeCompositeBuffer(bufferId: number): boolean;

  /**
   * Spawn a process (cancellable)
   */
  spawnProcess(command: string, args: string[], cwd: string | null): ProcessHandle<string>;

  /**
   * Spawn a background process (cancellable)
   */
  spawnBackgroundProcess(command: string, args: string[], cwd: string | null): ProcessHandle<string>;
}
